# Generated by Django 5.2.7 on 2026-01-20 14:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nidn', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('no_hp', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('homebase', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('npm', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mk', models.CharField(max_length=100)),
                ('kode_mk', models.CharField(max_length=10, unique=True)),
                ('sks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('semester', models.PositiveSmallIntegerField()),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_kuliah', to='mahasiswa.dosen')),
                ('mahasiswa', models.ManyToManyField(blank=True, related_name='mata_kuliah', to='mahasiswa.mahasiswa')),
            ],
        ),
    ]
